name: ARM Template Check

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      logicapp: ${{ steps.filter.outputs.logicapp }}
      alertrule: ${{ steps.filter.outputs.alertrule }}
      rbacrole: ${{ steps.filter.outputs.rbacrole }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            logicapp:
              - 'Templates/Logic_App/**'
            alertrule:
              - 'Templates/Alert_Rule/**'
            rbacrole:
              - 'Templates/RBAC_Role/**'

  logicapp:
    needs: changes
    if: ${{ needs.changes.outputs.logicapp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Logic App ARM Templates - path
        id: pathtest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: ./Templates/Logic_App
      - name: Test result - path
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.pathtest.outputs.results)) }}"

  alertrule:
    needs: changes
    if: ${{ needs.changes.outputs.alertrule == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Alert Rule ARM Templates - path
        id: pathtest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: ./Templates/Alert_Rule
      - name: Test result - path
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.pathtest.outputs.results)) }}"

  rbacrole:
    needs: changes
    if: ${{ needs.changes.outputs.rbacrole == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test RBAC Role ARM Templates - path
        id: pathtest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: ./Templates/RBAC_Role
      - name: Test result - path
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.pathtest.outputs.results)) }}"
      
      